apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limits-in-uat
  namespace: uat-env
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        memory: 256Mi
        cpu: 0.5
      type: Container