apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: cronjob-demo
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob-demo
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronjob-demo
            image: hintcnuie/cronjob-demo
            args: ["100"]