apiVersion: v1
kind: Pod
metadata:
  name: pod-with-mem-cpu-quota
  namespace: uat-env
spec:
  containers:
  - name: pod-with-mem-cpu-quota-c1
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu:  "800m"
      requests:
        memory: "600Mi"
        cpu:  "400m"