apiVersion: v1
kind: Pod
metadata:
  name: pod2-with-mem-cpu-quota
  namespace: uat-env
spec:
  containers:
  - name: pod2-with-mem-cpu-quota-c1
    image: nginx
    resources:
      limits:
        memory: "1Gi"
        cpu:  "800m"
      requests:
        memory: "700Mi"
        cpu:  "400m"